version: '3.8'

services:

  db:
    image: postgres:12
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
volumes:
  pg-data:
