version: "3.8"

services:
  spark-master:
    image: "k8s.gcr.io/spark:1.5.1_v3"
    command: ["/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"]
    environment:
      SPARK_DAEMON_MEMORY: 1g
      SPARK_MASTER_HOST: localhost
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    ports:
    - 7077:7077
    - 8080:6066
    - 6066:6066
    
